# Generated by Django 5.2.4 on 2025-07-12 21:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
        ('movies_orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='users',
            field=models.ManyToManyField(related_name='ordered_movies', through='movies_orders.MovieOrder', to=settings.AUTH_USER_MODEL),
        ),
    ]
